baseURL = "https://mai0li.github.io/"
languageCode = "en"
title = "InnerSpeaker"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
#disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics = "UA-122808963-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/mai0li"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"


# Add your own params here
[params]
  author = "Pedro Maioli"
  avatar = "https://avatars1.githubusercontent.com/u/7331302?s=460&v=4"
  seotitle = "InnerSpeaker"
  subtitle = "notes on information security"
  description = "iOS, macOS and Linux security researcher. Computer Science Graduate @ UESB. 25."
  paginate = 10

  # Choose your social networks
  email = "opponent at protonmail d0t c0m"
  github = "mai0li"
  twitter = "oakle"
  #linkedin = "linkedin_username"
  #weibo = "weibo_username"
  #wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  medium = "oakle"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  changyan = false
  #hangyanId = "cyt3toRiB"
  #changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "64WN4sgvTVdE8kim7yi2jGHWxpiVRxktflm9A52WeUw"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "59334F67CF537C0638E739FF1A938E21"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
